Repository micronaut-projects/micronaut-neo4j, pull requests merged in 2020-09, with the labels that each got.

#61 doc: point to github releases
  src/main/docs/guide/introduction.adoc
  src/main/docs/guide/releaseHistory.adoc
  src/main/docs/guide/toc.yml
Labels: type: docs

#62 checkstyle: swap order to fix checkstyle
  neo4j-bolt/src/main/java/io/micronaut/neo4j/bolt/health/Neo4jHealthIndicator.java
Labels: type: improvement

#63 ci: set github branch to 3.0.x
  gradle.properties
Labels: relates-to: build

#15 Upgrade to Micronaut 2.x
  build.gradle
  gradle.properties
  neo4j-bolt/build.gradle
Labels: relates-to: build

#64 build: downgrade neo4j version to 4.0.3
  gradle.properties
Labels: type: dependency-upgrade

#68 [neo4j] Update common files for branch 3.0.x
  .github/workflows/gradle.yml
Labels: relates-to: build

#67 [neo4j] Update common files for branch master
  .github/workflows/gradle.yml
Labels: relates-to: build

#69 Bump up micronaut test to 2.0.0
  gradle.properties
Labels: type: dependency-upgrade
